# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "environments/prod/debug/terraform.tfstate"
    resource_group_name  = "terraform"
    storage_account_name = "tfstate1138"
    subscription_id      = "3e78e84b-6750-44b9-9d57-d9bba935237a"
  }
}
